export const navbarLinks = [
    {
        id:1,
        label:"Home",
        href:"/"
    },
    {
        id:2,
        label:"Services",
        href:"/services"
    },
    {
        id:3,
        label:"About",
        href:"/about"
    },
    {
        id:4,
        label:"Contact",
        href:"/contact"
    },
]